# Generated by Django 3.2.8 on 2022-10-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Title',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
