# Generated by Django 3.2.8 on 2022-09-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_active_todo_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='TODO',
        ),
    ]
