# Generated by Django 3.2.8 on 2022-10-16 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0002_alter_project_title'),
        ('users', '0003_auto_20220927_1231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
